### ISSUE TITLE
use case: metronome

### ISSUE THREAD

**Issue by lukepighetti** [alnitak/flutter_soloud#100]
I have yet to find a flutter package that can keep time accurately enough for use as a metronome. I think we should add such an example to flutter_soloud to both ensure the package maintains best-in-industry playback scheduling accuracy, but to also show people what techniques are needed to play with accuracy

**Comment by alnitak** [comment]
Hi @lukepighetti, thanks for your feedback!

Some brief examples are expected soon. We will open an issue to ask which one could be more relevant for the devs.
Meanwhile, I would refer you to my reply of #99 regarding this issue.

**Comment by lukepighetti** [comment]
do you have any immediate recommendations for how to get the best metronome like performance out of flutter_soloud?

**Comment by alnitak** [comment]
> do you have any immediate recommendations for how to get the best metronome like performance out of flutter_soloud?

IIRC a good choice is to set a buffer of 512 (instead of the default 2048) [here](https://github.com/alnitak/flutter_soloud/blob/95e367161b3dddf2964e4c1403929fb3a34f4d46/src/player.cpp#L45).
Of course, there is some troubles because you need to clone this repo locally and point it to your app's `pubspec.yaml` after modifying `player.cpp`.

I also think you could try using the `SoLoud.play([your-short-metronome-sound])` inside a `Timer.periodic()`.

Let me know!

**Comment by alnitak** [comment]
I tried to make a metronome using a buffer of 512 and since the web platform is almost ready, I made the example available [here](https://marcobavagnoli.com/flutter_soloud_metronome/).

<details open>
<summary>I tried something like this</summary>

```dart

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  /// Initialize the player
  await SoLoud.instance.init();

  runApp(
    const MaterialApp(
      home: Metronome(),
    ),
  );
}

class Metronome extends StatefulWidget {
  const Metronome({super.key});

  @override
  State<Metronome> createState() => _MetronomeState();
}

class _MetronomeState extends State<Metronome> {
  /// delay between ticks.
  final delay = ValueNotifier<int>(100);

  /// duration of the tick sound.
  final tickDurationMs = ValueNotifier<int>(45);

  Timer? timer;
  AudioSource? tick;
  SoundHandle? tickHandle;

  @override
  void initState() {
    super.initState();
    SoLoud.instance
        .loadWaveform(WaveForm.fSquare, true, 0.25, 1)
        .then((value) async {
      final octave = 2;
      final noteIndex = 0;
      final startingFreq = 55.0 * (pow(2, (12 * octave) / 12));
      final freq = startingFreq * (pow(2, noteIndex / 12));

      tick = value;
      
      /// start playing the tick in a paused state, so it can be 
      /// unpaused/paused in the `Timer` callback.
      tickHandle = await SoLoud.instance.play(tick!, paused: true);

      SoLoud.instance.setWaveformFreq(tick!, freq);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Stack(
        children: [
          Padding(
            padding: const EdgeInsets.all(16),
            child: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  const Text('Metronome example',
                      textScaler: TextScaler.linear(3)),
                  const SizedBox(height: 32),
                  ValueListenableBuilder<int>(
                    valueListenable: delay,
                    builder: (_, ms, __) {
                      return Row(
                        children: [
                          Text('delay ms: $ms  BPM: ${60000 ~/ ms}'),
                          Expanded(
                            child: Slider.adaptive(
                              min: 15,
                              max: 500,
                              value: ms.toDouble(),
                              onChanged: (value) {
                                delay.value = value.toInt();
                                start();
                              },
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                  ValueListenableBuilder<int>(
                    valueListenable: tickDurationMs,
                    builder: (_, duration, __) {
                      return Row(
                        children: [
                          Text('tic duration ms $duration'),
                          Expanded(
                            child: Slider.adaptive(
                              min: 15,
                              max: 500,
                              value: duration.toDouble(),
                              onChanged: (value) {
                                tickDurationMs.value = value.toInt();
                                start();
                              },
                            ),
                          ),
                        ],
                      );
                    },
                  ),
                ],
              ),
            ),
          ),
        ],
      ),
    );
  }

  void start() {
    timer?.cancel();
    timer = Timer.periodic(Duration(milliseconds: delay.value), (_) {
      if (tickHandle != null) {
        SoLoud.instance.setPause(tickHandle!, false);
        SoLoud.instance.schedulePause(
          tickHandle!,
          Duration(milliseconds: tickDurationMs.value),
        );
      }
    });
  }
}
```

</details>

Soon there will be there will be the option to choose the buffer size while initializing the player.

**Comment by lukepighetti** [comment]
Some things I noticed using this on iOS simulator

- 400 bpm clearly shows drift issues
- tic duration cannot be less than 47 ms

**Comment by kelegorm** [comment]
Hi! About perfect metronome.

To achieve a truly precise metronome in Flutter, audio must be handled at the lowest level. Using a regular audio packages like soloud or other often results in timing drift because sounds are scheduled in whole buffer increments, which rarely align perfectly with the desired tempo. Simply rounding to the nearest buffer causes audible jitter, especially at higher BPMs.

Even if you could make buffer like 256 samples it's will be ~5ms. My android allows only 512 samples, which is ~10ms.

The correct approach is to process audio in a real-time callback, where each buffer is filled manually. Instead of playing the sound at the start of a buffer, the metronome must place the click sample at the exact position within the buffer, ensuring sample-accurate timing.

I do that with oboe, which allows me set desired buffer size and provides such callback for each buffer. And I wrote bunch of my own c++ code to work with that.

Even if you make buffer like 256 samples (on my android the lowest is 512 though) it's will be ~5ms on tempo 110 bpm, or 10ms if buffer is 512.

**Comment by alnitak** [comment]
Hi @kelegorm,

this is an interesting topic for me. Also replying to #78

Have you taken a look at the [metronome](https://github.com/alnitak/flutter_soloud/blob/main/example/lib/metronome/metronome.dart) example? (I have done also a [web example](https://marcobavagnoli.com/flutter_soloud_metronome/)). But maybe I think it is not what you want to achieve because for sure a bit of latency is present, I didn't try to see how much lag there is from a `tic` to another `tic`, but I think is less than 10ms(?)

There could be a way to do something you described you done with oboe. In the version 3.0.0-pre.1 there is the new BufferStream which you can use to fill a buffer that will be played while adding new audio data:
1. set a buffer type
2. add as much PCM audio data as you want and play it even after the first audio data added
3. set the buffer as ended

By doing 3. you will tell SoLoud that the sound will not be able to receive more data, just to have a way to get the `sound ended` callback.

As you can imagine, continuously sending data will consume a lot of memory also because even if you set the buffer to use signed 8 bits, SoLoud will treat them as float 32 bits. To resolve this is almost ready in PR #176 which can play only one instance of the sound and will free the memory of the audio already played. You can look at the [setBufferStream](https://github.com/alnitak/flutter_soloud/blob/3713a47c10bae3e5928c9c294ca8e23830882241/lib/src/soloud.dart#L719) and [addAudioDataStream](https://github.com/alnitak/flutter_soloud/blob/3713a47c10bae3e5928c9c294ca8e23830882241/lib/src/soloud.dart#L859C8-L859C26) docs for more info.

For your perfect metronome, I would try doing:
1. set a buffer type
2. add the PCM audio data for one `tic`
3. set the buffer as ended
4. play it in a loop

Let me know your thoughts and findings!

**Comment by kelegorm** [comment]
Hi @alnitak,

Thanks for your reply! I’m digging through the buffer docs right now and noticed that both setBufferStream and the onBuffering callback only offer time-based parameters (like maxBufferSizeDuration) instead of the buffer size in frames. I was thinking it might be more straightforward if the buffer size were defined in frames.

What do you think about this approach?

**Comment by alnitak** [comment]
Hi @kelegorm ,

the buffer size is only meant to set a memory limit for the sound. The buffer size parameter doesn't allocate that memory and the sound will use only the memory for the samples you have added.

The way the `onBuffering` callback works is this:
1. `setBufferStream` with your use-case parameters
2. on receiving audio data (ie from the web) use `addAudioDataStream` to add them and when receiving the 1st chunk start to play it
3. if the playback reaches the end of data and the `setDataIsEnded` has not been set yet, the callback is triggered with a `isBuffering=true` state.
4. the pause state will persist till new audio data is added and it reaches the need to fill `bufferingTimeNeeds` seconds. When there is enough audio data to play, the callback is triggered again with an `isBuffering=false`

The memory will grow for each call to `addAudioDataStream` and if it reaches `maxBufferSizeDuration` the `setDataIsEnded` is called automatically. You can also free the memory that has been already played by setting `bufferingType: BufferingType.released`. To understand how this works I've made a gif [here](https://github.com/alnitak/flutter_soloud/tree/main#opus-format-for-streaming). 

As you can see, this functionality is not meant to be used for an audio mixer or sequencer, the latency could be high. There is no direct access to read/write the audio buffer. Maybe in the near future (Flutter 4?) there will be some chances to have a way to manage a shared memory between threads (your Flutter isolate thread will be able to read native audio buffer in another thread) which is a mandatory feature for audio plugins.

Meanwhile, you could try to see the [generate.dart](https://github.com/alnitak/flutter_soloud/blob/main/example/lib/buffer_stream/generate.dart) example that generates some tones within an isolate.
