### ISSUE TITLE
fix: Possible crash with EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0x1166800a0

### ISSUE THREAD

**Issue by filiph** [alnitak/flutter_soloud#117]
**Description**

I got the following exception, reported by Sentry. I can't vouch for the bug since it was raised in debug (so maybe it's something that happened because of hot reload or something like that). But I file it anyway in case you have ideas.

![Screenshot 2024-08-21 at 20 33 21](https://github.com/user-attachments/assets/dc293f1d-3ca2-4a4d-bb66-f6d3ca0cad6f)

![Screenshot 2024-08-21 at 20 34 02](https://github.com/user-attachments/assets/9a2f3403-409a-4e93-a502-151499c75c4d)

Actually, now that I'm looking at the "breadcrumbs" (basically log history), it seems that this might have happened when I closed the app and the app tried to play a sound (the click sound of the "EXIT" button) while the app was being shut down.

Not sure if this is addressable, so feel free to close this

**Steps To Reproduce**

1. Try to create a condition where the app is `exit()`ing while a `SoLoud::on_notification` is called.

**Expected Behavior**

Event is ignored because SoLoud is (hopefully?) being shut down or is already shut down.

**Comment by alnitak** [comment]
Oh WOW! What makes me think is the first line of your screenshot: "Crashed in non-app", which is odd I think.

My thought is that a hot reload does this:
1. the `SoLoud.init()` method is called just after a hot reload
2. since the `init()` method sees the player is already initialized, it will `deinit()` it
3. meanwhile the state changes and the `SoLoud::on_notification` didn't realize yet a new address of the newly initialized player

Or maybe after a hot reload the Flutter main isolated is terminated and re-executed, but the audio thread is not yet. So the state changes and the old audio thread fires the callback that doesn't exist anymore.

I would leave this issue open for a while to see also if that state notification can be useful in the future because now it's not.

Thanks for your finding.

**Comment by alnitak** [comment]
I tried to use Sentry and I didn't see what you got. At least on Linux and Android.

Thinking about this, I created the branch `state_changed` that hopefully could fix this.

@filiph can you please try to use that branch to see if the error persists?

**Comment by filiph** [comment]
The thing is, I don't think I can reliably reproduce the issue. I didn't even notice it until seeing it much later in Sentry. I'm pretty sure the app closed just fine from the perspective of the user.

Feel free to close this for now. At the very least, it's good to have it here for SEO so that people searching for "EXC_BAD_ACCESS soloud" will get here.
