### ISSUE TITLE
docs: Playing a sound twice

### ISSUE THREAD

**Issue by Taormina** [alnitak/flutter_soloud#143]
**Description**

If I load a sound and play it twice too quickly back to back, the app will complain loudly. Since 

> Multiple voices, playing different or even the same sound multiple times on top of each other

is a listed feature, it would be good to have an example of how to do this.

I have helper methods below that try to only load each sound file once. That part is working fine, but if I try to re-use the source too quickly, I get an error about the source already existing in the `activeSounds` list. SFX and Vibrations are enums from my own code.

```
  Map<String, AudioSource> sounds = {};

  Future<AudioSource> getSource(String filename) async {
    if (!sounds.containsKey(filename)) {
      sounds[filename] =
          await SoLoud.instance.loadAsset('assets/audio/$filename');
    }
    return sounds[filename]!;
  }
  
    void playSound(SFX sound, Vibrations vibrations) async {
    final source = await getSource(sound.fileName);
    SoLoud.instance.play(source, volume: sfxVolume);
    if (vibrationsOn) {
      switch (vibrations) {
        case Vibrations.light:
          HapticFeedback.lightImpact();
        case Vibrations.medium:
          HapticFeedback.mediumImpact();
        case Vibrations.heavy:
          HapticFeedback.heavyImpact();
        case Vibrations.none:
        // no-op
      }
    }
  }
 ```
 
 ```
 Unhandled Exception: 'package:flutter_soloud/src/soloud.dart': Failed assertion: line 819 pos 12: 'filtered.length == 1': Duplicate sounds found #0 _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:50:61)
 ```
 
I was hoping the changes in 2.1.6 might've helped, but nothing really has changed. The actual sound is a quick thunk sound and doesn't crash out the app or anything but the sound won't play and that message is printed. I have to be going pretty quickly to trigger it. I've printed activeSounds and can see the number of activeSounds per soundHash it thinks it has (0 or 1) but I'm not quite sure what to do.

**Requirements**

- A documented example of how to play the same sound over top of itself.

**Comment by alnitak** [comment]
Hi @Taormina,

when you play a sound it needs some time to have back its `SoundHandle` which is unique but in sequence. I really think that the assert is thrown because a previous call to play has not been finished and the second call returns the `SoundHandle` already given to the first (or vice versa). For this reason, the `play` method is a Future.
I tried your example without the `await play()` but I didn't get the assert error, but just an exception. Maybe on another device could happen what you have experienced.

Could you please try to `await` the play method and tell me if you still have the issue?

If you are looking for some examples, [this project](https://github.com/alnitak/flutter_soloud_example) is available.

**Comment by Taormina** [comment]
The `await` seems to have cleared up my issue! Great catch. If this resurfaces I'll let you know, but thanks for the help!
