### ISSUE TITLE
feat: schedule play

### ISSUE THREAD

**Issue by lukepighetti** [alnitak/flutter_soloud#99]
I noticed we have scheduleStop and scheduleStart, but I'm having a hard time figuring out how to schedule a play.

The reason for this is to create a metronome that does not have any drift. I have not found an audio package that can handle this use case.

**Comment by alnitak** [comment]
Hi @lukepighetti,

I think this is somehow related to #78. The summary of that issue is related to the latency caused by the audio buffer size. Actually is not yet possible to change the buffer size within the current APIs, but only by changing its default value in a .cpp file. Hope to add this feature soon, just after the web platform will be supported!

**Comment by alnitak** [comment]
With PR #105 I think this can be closed. In the upcoming #110, there is also a [metronome example](https://github.com/alnitak/flutter_soloud/blob/pitch/example/lib/metronome/metronome.dart) that can be used within the current `main` branch.

@lukepighetti, feel free to reopen if it doesn't fit your expectations.
